internal object Versions {
    const val androidxCore = "1.7.0"
    const val composeCompiler = "1.2.0"
    const val compose = "1.1.1"
    const val composeActivity = "1.5.0"
    const val lifecycle = "2.4.1"
    const val hilt = "2.42"
    const val hiltNavigationCompose = "1.0.0"
    const val coroutines = "1.6.4"
    const val room = "2.4.2"
    const val timber = "5.0.1"
    const val composeDestinations = "1.5.9-beta"
    const val junit = "4.13.2"
    const val androidxJunit = "1.1.3"
    const val espressoCore = "3.4.0"
    const val fireStore = "24.2.1"
}
